version: '3'
services:
  setup:
    build: ./image
    volumes:
      - "./conf:/opt/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "network-config:/etc/network-setup"

volumes:
  network-config: